apache/sdap-nexus

CONTRIBUTING.md
This issue addresses https://issues.apache.org/jira/browse/SDAP-6
=> SDAP-6 Create CONTRIBUTE.md for all SDAP repositories

analysis/.idea/analysis.iml, analysis/.idea/encodings.xml, analysis/.idea/misc.xml, analysis/.idea/modules.xml, client/.gitignore, client/.idea/client.iml, client/.idea/encodings.xml, client/.idea/misc.xml, client/.idea/modules.xml, data-access/.gitignore, data-access/.idea/data-access.iml, data-access/.idea/encodings.xml, data-access/.idea/misc.xml, data-access/.idea/modules.xml, data-access/.idea/vcs.xml, nexus-ingest/nexus-sink/.gitignore, nexus-ingest/nexus-sink/gradle/wrapper/gradle-wrapper.properties, nexus-ingest/nexus-sink/gradlew.bat
Upated gitignore files using templates to ignore python, java, gradle, macOS, etc... files.
=> SDAP-14 updated gitignore files

README.md, docs/quickstart.rst
Added note about needing to re-export `VERSION`
=> SDAP-130 Add note to quickstart

docker/solr-single-node/Dockerfile, docker/solr-single-node/README.md, docker/solr-single-node/create-core.sh, docker/solr/Dockerfile
=> SDAP-109 Upgrade Solr server to version 7

data-access/config/schemas/cassandra/nexustiles.cql, docker/cassandra/Dockerfile, docker/cassandra/docker-entrypoint.sh
Update the image version to 2.2.
=> SDAP-139 Update Cassandra Image Version

analysis/webservice/algorithms_spark/HofMoellerSpark.py
This fixes several problems with the Spark Hovmoller Map algorithms:
(1) Currently the Hovmoller calculation is averaging latitudes or longitudes within individual tiles. However, depending on the search domain, unique lats/lons can be in multiple tiles.
(2) A time stamp can appear multiple times in the JSON response
(3) Lack of cos(lat) weighting when averaging over latitude
Note that the non-Spark Hovmoller algorithms have these same problems, but are considered deprecated and have not been fixed in this pull request.
=> SDAP-50 Fix incorrect Hovmoller Implementation

analysis/.idea/vcs.xml, analysis/webservice/webmodel.py, data-access/nexustiles/dao/SolrProxy.pyx
This PR covers "All times are provided in ISO 8601 compliant format (and seconds since epoch for backwards-compatibility)" in https://issues.apache.org/jira/browse/SDAP-89 for DataSeriesList
=> SDAP-98 Clean up and document DataSeriesList

analysis/webservice/algorithms_spark/TimeAvgMapSpark.py
This PR covers 
- "All times are provided in ISO 8601 compliant format (and seconds since epoch for backwards-compatibility)"
- "Common values use the same name (e.g. use 'mean' for all means instead of 'mean' in some places and 'avg' in others)"
in https://issues.apache.org/jira/browse/SDAP-89 for TimeAvgMapSpark
=> SDAP-95 Clean up and document TimeAvgMapSpark

analysis/webservice/algorithms_spark/DailyDifferenceAverageSpark.py, analysis/webservice/webmodel.py, docker/nexus-webapp/Dockerfile
Getting an error when trying to convert the startTime to ISO format. May also be affecting other algorithms.
=> SDAP-150 Error processing dailydifferenceaverage

client/nexuscli/nexuscli.py, client/nexuscli/test/nexuscli_test.py
This reverts commit a888889f825c363aba8df43f0a94b3eec9a7dd22.
=> Revert "SDAP-152 Error in nexus client (#39)"

client/nexuscli/nexuscli.py, client/nexuscli/test/nexuscli_test.py
Reverts apache/incubator-sdap-nexus#41
=> Revert "SDAP-152 Error in nexus client"

analysis/webservice/NexusHandler.py, analysis/webservice/algorithms_spark/ClimMapSpark.py, analysis/webservice/algorithms_spark/CorrMapSpark.py, analysis/webservice/algorithms_spark/TimeAvgMapSpark.py, analysis/webservice/algorithms_spark/TimeSeriesSpark.py, analysis/webservice/webmodel.py
* Removed spark configuration, added nparts configuration, and autocompute parallelism for spark-based time series.
* SDAP-151 Determine parallelism automatically for Spark analytics
=> SDAP-151 Determine parallelism automatically for Spark analytics (#50)

tools/doms/doms_reader.py
* SDAP-192 Created DOMS netCDF reader tool.
* SDAP-192 DOMS netCDF reader updated to use num2date function to get datetime object from timestamp.
* SDAP-192 Added logging to DOMS netCDF reader tool.
* SDAP-192 Miscellaneous variable updates with DOMS netCDF reader.
* SDAP-192 'try/except' blocks around 'with' statements for netCDF and CSV file handling. Changed name of CSV file output from main. Moved print statement.
* SDAP-192 Changed print to LOGGER.info in DOMS netCDF reader.
=> SDAP-192 Created DOMS netCDF reader tool. (#68)

analysis/.idea/inspectionProfiles/Project_Default.xml, analysis/tests/algorithms_spark/Matchup_test.py, analysis/webservice/algorithms_spark/Matchup.py
Use time to determine closest point if two points are same distance from primary.
=> SDAP-196: take time into account when finding closest match

analysis/webservice/algorithms/doms/DomsInitialization.py, analysis/webservice/algorithms/doms/ResultsStorage.py, analysis/webservice/algorithms_spark/Matchup.py
support querying with quality flags in DOMS
=> SDAP-144 add quality flag support for DOMS 

analysis/webservice/algorithms/doms/BaseDomsHandler.py
Fixed the following issues/bugs:
1 - Removed quality information from satellite variables in the csv output
 2 - Add comment attribute to WindComponent to explain it's relation to windU and windV 
3 - Add api query to DOMS headers (netcdf and csv)
=> SDAP-204: Fix quality flag bugs

docker/nexus-webapp/install_conda.sh, docker/nexus-webapp/mesos/agent/docker-entrypoint.sh, docker/nexus-webapp/mesos/base/Dockerfile, docker/nexus-webapp/mesos/webapp/docker-entrypoint.sh, docker/nexus-webapp/standalone/Dockerfile, docker/nexus-webapp/standalone/docker-entrypoint.sh
Updated anaconda and used new option `conda config --set channel_priority strict` to fix some of the errors. Also created a conda environment to execute inside of instead of using base.
=> SDAP-207 GDAL Import error

tools/doms/README.md, tools/doms/doms_reader.py
SDAP-192 Updating the documentation for the DOMS netCDF reader tool, adding a README.md file.
=> SDAP-192 Create DOMS netCDF reader tool

docs/quickstart.rst
A few updated in the quickstart guide for a single node installation after I have tested the deployment on my laptop.
=> SDAP-216: Update the quickstart guide

analysis/setup.py, analysis/webservice/NexusHandler.py, analysis/webservice/algorithms_spark/HofMoellerSpark.py, analysis/webservice/algorithms_spark/TimeAvgMapSpark.py, analysis/webservice/algorithms_spark/TimeSeriesSpark.py, analysis/webservice/metrics/MetricsField.py, analysis/webservice/metrics/MetricsRecord.py, analysis/webservice/metrics/__init__.py, data-access/nexustiles/nexustiles.py, docker/nexus-webapp/Dockerfile
=> Performance metrics logging

analysis/webservice/algorithms_spark/TimeSeriesSpark.py
https://issues.apache.org/jira/browse/SDAP-258
=> SDAP-258: Use pre-computed climatologies for deseason algorithm

docker/nexus-webapp/Dockerfile, tools/deletebyquery/deletebyquery.py
https://issues.apache.org/jira/browse/SDAP-292
=> Delete script support cassandra auth

analysis/webservice/algorithms_spark/HofMoellerSpark.py, analysis/webservice/algorithms_spark/TimeSeriesSpark.py, analysis/webservice/algorithms_spark/utils.py, analysis/webservice/webmodel/NexusRequestObject.py, analysis/webservice/webmodel/RequestParameters.py
https://issues.apache.org/jira/browse/SDAP-294
=> SDAP-294: Date normalization

helm/Chart.yaml, helm/requirements.yaml, helm/values.yaml
https://issues.apache.org/jira/browse/SDAP-299
=> SDAP-299: Update obsolete helm repo urls (fix for breaking change)

analysis/webservice/algorithms/doms/BaseDomsHandler.py, analysis/webservice/algorithms/doms/ResultsPlotQuery.py, analysis/webservice/algorithms/doms/ResultsRetrieval.py, analysis/webservice/algorithms/doms/ResultsStorage.py, analysis/webservice/algorithms/doms/histogramplot.py, analysis/webservice/algorithms/doms/insitusubset.py, analysis/webservice/algorithms/doms/mapplot.py, analysis/webservice/algorithms/doms/scatterplot.py, analysis/webservice/algorithms/doms/subsetter.py, analysis/webservice/algorithms_spark/Matchup.py, analysis/webservice/nexus_tornado/request/renderers/NexusCSVRenderer.py, analysis/webservice/nexus_tornado/request/renderers/NexusZIPRenderer.py, analysis/webservice/webapp.py, data-access/setup.py, docker/nexus-webapp/Dockerfile
[Jira ticket](https://issues.apache.org/jira/browse/SDAP-305)
This branch adds the changes needed to get AVHRR OI matchup working on Kubernetes. 
Changes:
- Added missing `tile_service_factory` param to `/domsresults`
- For doms endpoints, instead of just reading config directly and using those values, use the values passed in during runtime and overwrite. This is consistent with how the working non-doms endpoints are doing things.
- Updated pyspark to 3.1.1
- Updated kubernetes client to 4.12.0
This is deployed on bigdata. Example:
```
https://bigdata.jpl.nasa.gov/nexus/match_spark?primary=avhrr-l4-glob-v2-daily-ncei-ghrsst-sstblend-avhrr-oi-glob-v020-fv020&startTime=1442102400&endTime=1442288800&tt=86400&rt=1000&b=-67.43499976462817,60.39585573909287,-50.681836983854154,76.72666987833477 …
```
=> SDAP-305: Get current match up working with AVHRR OI data that is currently ingested in the bigdata cluster

analysis/webservice/algorithms/doms/BaseDomsHandler.py, analysis/webservice/algorithms/doms/DomsInitialization.py, analysis/webservice/algorithms/doms/ResultsPlotQuery.py, analysis/webservice/algorithms/doms/ResultsRetrieval.py, analysis/webservice/algorithms/doms/ResultsStorage.py, analysis/webservice/algorithms/doms/histogramplot.py, analysis/webservice/algorithms/doms/insitusubset.py, analysis/webservice/algorithms/doms/mapplot.py, analysis/webservice/algorithms/doms/scatterplot.py, analysis/webservice/algorithms/doms/subsetter.py, analysis/webservice/algorithms_spark/Matchup.py, analysis/webservice/nexus_tornado/request/renderers/NexusCSVRenderer.py, analysis/webservice/nexus_tornado/request/renderers/NexusZIPRenderer.py, analysis/webservice/webapp.py, data-access/setup.py, docker/nexus-webapp/Dockerfile
Value can be : True [default] / False
Admin must setup the value to False if the Cassandra user has restricted permissions on the cluster.
The value will be checked before creating DOMS keyspace.
If the user is not permitted to create a keyspace on the Cassandra cluster, then the keyspace will be directly selected & the tables will be created (if needed).
Tested by dropping an existing table ; when Nexus starts, the table is correctly created.
=> SDAP-304 : Added optional domsconfig "create_keyspace_granted" 

analysis/webservice/algorithms_spark/Matchup.py
I noticed the following pyproj call was deprecated:
```python
pyproj.transform(p1=lonlat_proj, p2=aeqd_proj, x=x, y=y)
```
I updated this call to the following:
```python
aeqd_proj(x, y)
```
which no longer throws a deprecation warning. I also noticed it's significantly faster. Here's a minimal example I threw together:
```python
matchup_center_lon=-86.36720670954534
matchup_center_lat=19.85014715590842
y=22.1
x=-94.0
lonlat_proj = pyproj.Proj(proj='lonlat')
aeqd_proj = pyproj.Proj(proj='aeqd', lon_0=matchup_center_lon, lat_0=matchup_center_lat)
pyproj.transform(p1=lonlat_proj, p2=aeqd_proj, x=x, y=y)  # The old way
aeqd_proj(x, y)  # The new way
```
Both return the same result, but the first transform takes 0.073577404 seconds and the second takes 0.000022650 seconds.
I integrated this …
=> SDAP-312: Improved UTM reprojection speed

analysis/webservice/apidocs/index.html, analysis/webservice/apidocs/openapi.yml, analysis/webservice/webapp.py
https://bugs.earthdata.nasa.gov/browse/CDMS-77
https://bugs.earthdata.nasa.gov/browse/CDMS-79
=> SDAP-332: OpenAPI Documentation + SwaggerUI for Matchup Endpoints

helm/templates/_helpers.tpl
See ticket https://issues.apache.org/jira/browse/SDAP-358
The correction has been initially found by @jjacob7734
=> remove hyphen to avoid carriage return from being removed

analysis/webservice/algorithms/DataInBoundsSearch.py
This should fix the issue in data-in-bounds api endpoint
=> Add toJson in data-in-bounds api

analysis/tests/algorithms/test_base_doms_handler.py, analysis/webservice/algorithms/doms/BaseDomsHandler.py, analysis/webservice/algorithms/doms/ResultsStorage.py, analysis/webservice/algorithms/doms/config.py, analysis/webservice/algorithms_spark/Matchup.py
Apache ticket: [SDAP-366](https://issues.apache.org/jira/browse/SDAP-366)
These changes fix the CSV output for matchup. The issue was that `doms.ResultStorage` was using the old json format, so I updated it to use the new json format.
Note: this does not fix the NetCDF output. The NetCDF output issue seems to be a bit more complicated so I'm going to continue working that separately.
Testing:
Matchup request:
```
{{big_data_url}}/match_spark?primary=MUR25-JPL-L4-GLOB-v04.2&startTime=2018-09-24T00:00:00Z&endTime=2018-09-30T00:00:00Z&tt=2592000&rt=1000&b=160,-30,180,-25&platforms=1,2,3,4,5,6,7,8,9&parameter=sst&depthMin=0&depthMax=5&matchOnce=true&secondary=icoads&resultSizeLimit=6000
``` 
Used execution ID from the above request to do `/domsresults` request:
``` …
```
=> SDAP-366: Fix CSV output for matchup

analysis/webservice/apidocs/dataset-populate.js, analysis/webservice/apidocs/openapi.yml
Fixes bug where a deselected parameter appears in queries
=> Hotfix: Handle mismatched dataset listing and specification example

CHANGELOG.md, analysis/webservice/algorithms/doms/config.py
For matchup validation, CDMS team would like to use https://doms.coaps.fsu.edu/ws/search/samos_cdms which has additional variables.
=> SDAP-372 Updated match_spark_doms to interface with samos_cdms endpoint

CHANGELOG.md, analysis/tests/algorithms/test_subsetter.py, analysis/webservice/algorithms/doms/insitu.py, analysis/webservice/algorithms/doms/subsetter.py, analysis/webservice/algorithms_spark/Matchup.py, analysis/webservice/apidocs/openapi.yml, data-access/nexustiles/model/nexusmodel.py, data-access/nexustiles/nexustiles.py
https://issues.apache.org/jira/browse/SDAP-371
- Renamed endpoint `/domssubset` -> `/cdmssubset`
- Updated openapi spec with "cdms" terminology
- Added unit tests for toZip and toCsv
- Moved `query_edge` function into a new python module `analysis/webservice/algorithms/doms/insitu.py` and changed "edge" terminology to "insitu"
- Updated matchup to use this, removed query_edge
- Updated subsetter to, rather than querying SDAP, use existing functions to query satellite and insitu data
- ZIP contains one CSV file per dataset. File is named like "\<dataset-name\>.csv"
- Added default of 0/5 for min/max depth because AWS insitu API requires those fields
In addition to unit tests also ran locally with the following request:
```
{{big_data_url}}/cdmssubset?dataset=ASCATB-L2-Coastal&parameter=sea_ …
```
=> SDAP-371: Fix domssubset API

CHANGELOG.md, analysis/webservice/algorithms/doms/config.py, analysis/webservice/algorithms/doms/insitu.py
https://issues.apache.org/jira/browse/SDAP-396
Added saildrone insitu API.
I haven't had much luck finding a request that results in a matchup. I'm trying to find overlap with a satellite dataset. insitu calls seem to be executed as expected, though.
=> SDAP-396: saildrone insitu

CHANGELOG.md, analysis/webservice/algorithms/doms/BaseDomsHandler.py
Latitude and longitude were switched.
=> Fix NetCDF output

CHANGELOG.md, helm/templates/ingress.yml
Potential fix for duplicate request issue
=> Bumped ingress timeouts to reflect increased AWS gateway timeout

CHANGELOG.md, analysis/webservice/algorithms/doms/insitu.py, analysis/webservice/algorithms_spark/Matchup.py
Matchup will fetch the insitu schema when it is needed instead of fetching on import.
=> Insitu schema

CHANGELOG.md, analysis/webservice/algorithms/doms/subsetter.py
Potential solution to issues with subsetting L2 data crashing the webapp due to memory exhaustion.
Verified new subsetter code with validation utility (comparing to OPeNDAP (L4) and Harmony (L2)) and results are consistent with existing code.
Additionally, I added some logging statements.
=> Updated cdmssubset to reduce memory consumption

CHANGELOG.md, analysis/setup.py, docker/nexus-webapp/Dockerfile
Used mamba to install nexus-analysis packages.
This change improved the build time for webapp Docker image to ~400 seconds.
=> SDAP-416: Improve speed of install of nexus-analysis package

docs/granule-download.sh
Part of #242 but adding script referenced in quickstart to master in advance to simplify running of quickstart guide during the release process
=> Added granule download script from #242 to master in advance

CHANGELOG.md, analysis/setup.py, analysis/webservice/algorithms_spark/Matchup.py, analysis/webservice/config/scheduler.xml, analysis/webservice/nexus_tornado/app_builders/SparkContextBuilder.py
_Note: This is branched off of SDAP-467. We should merge these branches like SDAP-455 -> SDAP-467 -> SDAP-473_
Implemented basic job prioritization in SDAP for matchup jobs. 
- Updated scheduling between pools to `FAIR`. Default in Spark is `FIFO`.
> Under fair sharing, Spark assigns tasks between jobs in a “round robin” fashion, so that all jobs get a roughly equal share of cluster resources [source](https://spark.apache.org/docs/latest/job-scheduling.html#scheduling-within-an-application)
- Created new `scheduler.xml` file which is where the two new pools are specified. For now, very simple "large" and "small" pools are used. In the future, we should consider adding more pools.
- If num primary tiles > threshold, use the "large" pool. The "large" pools is give much lower priority in …
=> SDAP-473: Job priorization

.asf.yaml, CHANGELOG.md
https://issues.apache.org/jira/browse/SDAP-483
=> SDAP-483: Added `.asf.yaml` to configure Jira auto-linking.

CHANGELOG.md, analysis/webservice/algorithms/doms/ResultsStorage.py
Returns code 404 if no matching execution found
=> Execution not found status code 404

CHANGELOG.md, analysis/webservice/algorithms/doms/ResultsStorage.py
Previously a single failure would cause the entire write to be retried. Now only retires the failed points
=> SDAP-485 - Improved writing to doms_data with very large numbers of points

CHANGELOG.md, analysis/webservice/algorithms/doms/DatasetListQuery.py, data-access/nexustiles/dao/SolrProxy.py
Example `/list` output:
```json
[
{
"shortName": "MUR25-JPL-L4-GLOB-v04.2", 
"title": "MUR25-JPL-L4-GLOB-v04.2", 
"tileCount": 30176, 
"start": 1533114000.0, 
"end": 1535792400.0, 
"iso_start": "2018-08-01T09:00:00+0000", 
"iso_end": "2018-09-01T09:00:00+0000", 
"spatial_extent": "-179.88,-82.38,179.88,89.88"
}, 
...
]
```
Example `/cdmslist` output:
```json
{
"data": {
"satellite": [
{
"shortName": "AVHRR_OI_L4_GHRSST_NCEI",
"title": "AVHRR_OI_L4_GHRSST_NCEI",
"tileCount": 3570,
"start": 1446336000.0,
"end": 1448841600.0,
"iso_start": "2015-11-01T00:00:00+0000",
"iso_end": "2015-11-30T00:00:00+0000",
"spatial_extent": "-179.88,-89.88,179.88,89.88",
"metadata": null
},
...
],
"insitu": [ ... ]
}
}
```
=> SDAP-508 - Report satellite dataset spatial extents in list endpoints

helm/values.yaml
Found this still open ticket while going through all the old tickets and was surprised nobody took care of it yet
=> SDAP-319 - Fixed typo

CHANGELOG.md
=> Added forgotten changelog entry

poetry.lock, pyproject.toml
Forgot required dependency for tomography endpoints
=> [Patch] Add missing dependency to pyproject.toml
