data-access/.gitignore
data-access/nexustiles/config/datastores.ini
data-access/nexustiles/dao/CassandraProxy.pyx
data-access/nexustiles/dao/DynamoProxy.pyx
data-access/nexustiles/dao/S3Proxy.pyx
data-access/nexustiles/nexustiles.py
data-access/requirements.txt
data-access/setup.py
data-access/tests/nexustiles_test.py
tools/deletebyquery/deletebyquery.py

This PR alters the data-access library for time series tiles. It now expects time series tiles to have an array for their time attribute instead of a single value.

SDAP-32 CassandraProxy time series tiles to support time arrays

---

client/nexuscli/nexuscli.py
client/nexuscli/test/nexuscli_test.py

Made use of session object optional

SDAP-121 Make use of session optional

---

analysis/webservice/NexusHandler.py

I fixed this by rewriting the SparkHandler (in NexusHandler.py) _find_global_tile_set method.  I now check for days in range first and then attempt to find the tile set from each day in range until I succeed.

SDAP-119 Fix bug that makes TimeAvgMapSpark appear to hang if there is no data in bounding box

---

docker/jupyter/Dockerfile

I modified the Jupyter Docker image to enable the NEXUS repo and branch to use to be configured at build time.  The build syntax for this feature is as follows: 
docker build --build-arg APACHE_NEXUS=https://github.com/my-repo.git --build-arg APACHE_NEXUS_BRANCH=my-branch -t my-image-tag .

SDAP-123 Allow Jupyter image to configure nexus repo at build time.

---

analysis/webservice/algorithms_spark/TimeSeriesSpark.py

This PR covers "All times are provided in ISO 8601 compliant format (and seconds since epoch for backwards-compatibility)" in https://issues.apache.org/jira/browse/SDAP-89 for TimeSeriesSpark

SDAP-96 Clean up and document TimeSeriesSpark

---

analysis/webservice/NexusHandler.py
analysis/webservice/algorithms_spark/ClimMapSpark.py
analysis/webservice/algorithms_spark/CorrMapSpark.py
analysis/webservice/algorithms_spark/TimeAvgMapSpark.py
analysis/webservice/algorithms_spark/TimeSeriesSpark.py
analysis/webservice/webmodel.py

The built-in NEXUS analytics timeSeriesSpark, timeAvgMapSpark, corrMapSpark, and climMapSpark got the desired parallelism from a job request parameter like "spark=mesos,16,32".  If that was omitted, we defaulted to "spark=local,1,1", which runs on a single core.  The new algorithms automatically determine the appropriate level of parallelism based on the job's Spark cluster configuration.  The job parameter called "spark" is no longer supported.  A new optional job parameter called "nparts" can be used to explicitly set the number of data partitions (e.g., "nparts=16").

SDAP-151 Determine parallelism automatically for Spark analytics

---

analysis/webservice/algorithms/doms/DomsInitialization.py
analysis/webservice/algorithms/doms/domsconfig.ini
data-access/nexustiles/config/datastores.ini
docker/nexus-webapp/standalone/docker-entrypoint.sh

- DomsInitialization is now able to instantiate a Cluster object by using the "post" argument in method signature
- default port (9042) is added in both domsconfig.ini & datastores.ini
- running a Docker container with "-e CASSANDRA_PORT=<some_other_port>" will let the webapp contact the cassandra cluster

SDAP-187 Unable to change cassandra port

---

analysis/webservice/algorithms/doms/BaseDomsHandler.py

The min and max attributes for lat and lon variables in the netcdf were not writing as floats. This was causing errors in the calculation and errors for the readers. This has been fixed
https://issues.apache.org/jira/browse/SDAP-205

SDAP-205: Lat/lon netcdf not writing as float

---

client/requirements.txt

This issue addresses https://issues.apache.org/jira/browse/SDAP-206

SDAP-206 remove pegged numpy version in nexuscli requirements.txt

---

client/nexuscli/nexuscli.py
docs/quickstart.rst

The function was converting date timestamp to iso format assuming the timestamp was in millisecond.
Instead we directly get the iso date string from the nexus service. No conversion is required.

SDAP 218: bug correction on start/end date from nexcusli.dataset_list() 

---

analysis/webservice/algorithms_spark/HofMoellerSpark.py
analysis/webservice/webapp_livy.py
data-access/requirements.txt
helm/values.yaml

[Apache Jira ticket](https://issues.apache.org/jira/browse/SDAP-154)
[Earthdata Jira ticket](https://bugs.earthdata.nasa.gov/browse/CDMS-46)
Made a few updates to address issues found while testing the Python3 changes.
- Fixed some import/casting issues in the code
- Upgraded `cassandra-driver` to 3.24.0 for compatibility with Python 3.8
- Upgraded `pysolr` to 3.24.0 for compatibility with Python 3.8
- Upgraded nexus-webapp version to `distributed.0.4.0` in helm/values.yaml, so the [new docker image](https://hub.docker.com/r/nexusjpl/nexus-webapp) is used in the kubernetes cluster. 
Note: There is another PR that is paired with this one [HERE](https://github.com/apache/incubator-sdap-nexusproto/pull/6) which these changes depend upon.

SDAP-154: Python 3

---

analysis/setup.py
analysis/webservice/algorithms/doms/DomsInitialization.py
analysis/webservice/algorithms/doms/ResultsStorage.py
analysis/webservice/algorithms_spark/Matchup.py
data-access/nexustiles/dao/CassandraProxy.py
data-access/nexustiles/nexustiles.py

[Jira ticket](https://issues.apache.org/jira/browse/SDAP-305)
In this branch, I've made the necessary fixes to get matchup working on AVHRR OI data. 
Sample request:
```sh
curl --request GET 'localhost:8083/match_spark?primary=avhrr-l4-glob-v2-daily-ncei-ghrsst-sstblend-avhrr-oi-glob-v020-fv020&startTime=1442102400&endTime=1442288800&tt=86400&rt=1000&b=-67.43499976462817,60.39585573909287,-50.681836983854154,76.72666987833477&platforms=1,2,3,4,5,6,7,8,9&parameter=sst&depthMin=0&depthMax=5&matchOnce=true&matchup=icoads'
```
Response:
```json
{
"executionId": "ca33871b-db76-492c-bc43-bbd7d4bfea7e",
"data": [
{
"sea_water_temperature": 276.22998046875,
"sea_water_temperature_depth": 0,
"sea_water_salinity": null,
"sea_water_salinity_depth": null,
"wind_speed": null,
"wind_direction": null, …
```

SDAP-305: Get current match up working with AVHRR OI data that is currently ingested in the bigdata cluster

---

tools/deletebyquery/deletebyquery.py
tools/deletebyquery/requirements.txt

Updated solrcloudpy dependency and removed eval so that deletebyquery tool works with Python 3.
Tested this locally and confirmed input works.
Before the change:
```
Query found 100254 matching documents. Continue? [y]/n/(s)ample: n
Traceback (most recent call last):
File "/Users/nchung/PycharmProjects/incubator-sdap-nexus/tools/deletebyquery/deletebyquery.py", line 269, in <module>
delete_by_query(the_args)
File "/Users/nchung/PycharmProjects/incubator-sdap-nexus/tools/deletebyquery/deletebyquery.py", line 92, in delete_by_query
if check_query(query):
File "/Users/nchung/PycharmProjects/incubator-sdap-nexus/tools/deletebyquery/deletebyquery.py", line 127, in check_query
do_continue = eval(input("Query found %s matching documents. Continue? [y]/n/(s)ample: " % num_found))
File "<string>", …
```

SDAP-308 Fixed deletebyquery.py to be compatible with Python 3

---

analysis/webservice/algorithms/ColorBarHandler.py
analysis/webservice/algorithms/MapFetchHandler.py
analysis/webservice/algorithms/doms/DatasetListQuery.py
analysis/webservice/algorithms/doms/MetadataQuery.py
analysis/webservice/algorithms/doms/StatsQuery.py
analysis/webservice/algorithms/doms/ValuesQuery.py

While looking through logs, I noticed some of the doms endpoints were leading to the following errors:
```
2021-05-23T16:11:03 - nexus - INFO - Received request GET /domsvalues (10.244.1.177)
2021-05-23T16:11:03 - tornado.application - ERROR - Uncaught exception GET /domsvalues (10.244.1.177)
HTTPServerRequest(protocol='http', host='mycluster', method='GET', uri='/domsvalues', version='HTTP/1.1', remote_ip='10.244.1.177')
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
result = await result
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
yielded = ctx_run(next, result)
File "/opt/conda/lib/python3.8/site-packages/nexusanalysis-1.6-py3.8.egg/webservice/nexus_tornado/request/handlers/Ne …
```

Added missing tile_service_factory param to NexusCalcHandlers endpoints

---

helm/templates/_helpers.tpl
helm/values.yaml

In this case the `path` becomes optional
This PR also uses the upgrades granule-ingester and collection-manager components (0.1.6)

make chart work with pre-existing data-volume (pvc)

---

analysis/tests/algorithms_spark/test_matchup.py
analysis/webservice/algorithms_spark/Matchup.py
data-access/nexustiles/dao/CassandraProxy.py
data-access/nexustiles/model/nexusmodel.py
data-access/nexustiles/nexustiles.py

https://issues.apache.org/jira/browse/SDAP-338
Added support for multi-var tiles in the matchup algorithm. This support exists for multi-variable swath and gridded tiles. 
I went back and forth a lot about the best way to do this. In the end, I decided the best way for now is to make it backwards compatible so the other algorithms can be updated as-needed. This means all algorithms should work as normal on single-var tiles, but would need to update their code to work with multi-var. 
An alternative idea would be to update our tile representation drastically, which would require all algorithms to be updated for both single and multi var tiles. This might be the 'right' way to do this at some point, but for now the approach I went with is the one with the smallest impact on other SDAP …

SDAP-338: Update match up implementation to support multi-variable tiles

---

analysis/tests/algorithms_spark/test_matchup.py
analysis/webservice/algorithms_spark/Matchup.py
analysis/webservice/apidocs/openapi.yml

- Updated matchup request param from `matchup` to `secondary`
- Updated matchup output `data` to either `primary` or `secondary`
- Updated `matchup` terminology to `secondary` in code for consistency.
- Updated unit tests to work with these changes.
- Updated OpenAPI spec to reflect changes.
Tested locally:
```
{{big_data_url}}/match_spark?primary=ASCATB-L2-Coastal&startTime=2017-02-28T12:03:16Z&endTime=2017-02-28T12:03:16Z&tt=86400&rt=100000&b=100,0,150,20&platforms=1,2,3,4,5,6,7,8,9&depthMin=0&depthMax=5&matchOnce=true&secondary=icoads
```
(results truncated)
```json
{
"executionId": "e9803ae1-bbe2-4fad-814e-ce42752183b3",
"data": [
{
"platform": "orbiting satellite",
"device": "radiometers",
"x": "133.93401",
"y": "15.697170000000002",
"point": "Point(133.93401 15.697170000000002)", …
```

SDAP-355: Update matchup parameter and output to use primary and secondary

---

docker/solr/Dockerfile
docker/solr/Readme.rst
helm/requirements.yaml
helm/templates/_helpers.tpl
helm/values.yaml

The helm chart is updated to use the bitnami stable chart instead of the incubator version previously.
The update requires the use of a specific docker solr image to have the JTS jar for geospatial support. The dockerfile is published there https://github.com/tloubrieu-jpl/solr-with-jts-docker.
The docker image still need to be published outside of tloubrieu dockerhub organization.
The update also requires an update of the granule ingester component for its connection to solr, see pull request https://github.com/apache/incubator-sdap-ingester/pull/50

change solr helm chart dependency to stable

---

analysis/webservice/apidocs/openapi.yml

Even though for DOMS/CDMS we've only documented the matchup endpoints, the OpenAPI spec isn't restricted to just matchup endpoints, so worth changing the title.

SDAP-332 Changed to use SDAP instead of DOMS for title

---

analysis/webservice/algorithms/DataInBoundsSearch.py

Current data-inbounds-search algorithm would throw error `NexusPoint' object has no attribute 'data_val'`. This is a quick fix to replace data_val to data_vals in data-inbounds-search algorithm.

Replace data_val with data_vals in data-in-bounds-search algorithm

---

docker/solr/Dockerfile
helm/requirements.yaml
helm/values.yaml

https://issues.apache.org/jira/browse/SDAP-364
Bump Solr version to address log4j vulnerability. Pushed bumped solr image to dockerhub: `nexusjpl/solr:8.11.1`
Note: This has not yet been tested. The cdms and bigdata deployments are not using the solr bitnami chart yet (that's new) so I'm still investigating the best way to do this.

SDAP-364: Upgrade Solr to 8.11.1

---

analysis/webservice/apidocs/dataset-populate.js
analysis/webservice/apidocs/index.html
analysis/webservice/apidocs/openapi.yml

Update SwaggerUI API documentation to display datasets available on the current Nexus node dynamically and independent of the API specification via a SwaggerUI plugin

SDAP-363: Update SwaggerUI to display list of available datasets dynamically

---

analysis/tests/algorithms_spark/test_timeseriesspark.py
analysis/webservice/algorithms_spark/TimeSeriesSpark.py

Apache ticket: [SDAP-318](https://issues.apache.org/jira/browse/SDAP-318)
This updates the timeSeriesSpark algorithm to use the bounding box (instead of polygon) to perform spatial searching on Solr. This is in line with how the other algorithms do spatial searching. 
**The issue**: Polygon search runs into an inherent issue with WKT strings where bounding boxes with > 180 difference between maxLon and minLon. This results in no tiles being returned from Solr, and an empty list being returned for the algorithm results. 
**The fix**: Update algorithm to use [get_tiles_bounded_by_box](https://github.com/apache/incubator-sdap-nexus/blob/6583534206a1d9dbfb1eb1bada50af6f3e09396a/data-access/nexustiles/nexustiles.py#L260) instead of [get_tiles_bounded_by_polygon](https://github.com/apache/incuba …

SDAP-318 Updated timeSeriesSpark algorithm to find tiles by bounding box instead of polygon

---

CHANGELOG.md
analysis/tests/algorithms_spark/test_matchup.py

Fixed failing matchup test. Matchup now uses 'lon' instead of 'x', which I forgot to update in the unit tests.

Fixed failing matchup unit test

---

analysis/README.md
analysis/conda-requirements.txt
analysis/setup.py
analysis/tests/redirect/collections-config.yaml
analysis/tests/webapp_test.py
analysis/webservice/algorithms/DataSeriesList.py
analysis/webservice/algorithms/doms/DomsInitialization.py
analysis/webservice/nexus_tornado/app_builders/HandlerArgsBuilder.py
analysis/webservice/nexus_tornado/app_builders/NexusAppBuilder.py
analysis/webservice/nexus_tornado/app_builders/RedirectAppBuilder.py
analysis/webservice/nexus_tornado/app_builders/SparkContextBuilder.py
analysis/webservice/nexus_tornado/app_builders/__init__.py
analysis/webservice/redirect/RedirectHandler.py
analysis/webservice/redirect/RemoteCollectionMatcher.py
analysis/webservice/redirect/__init__.py
analysis/webservice/webapp.py
data-access/nexustiles/dao/CassandraProxy.py
data-access/nexustiles/dao/SolrProxy.py
docker/nexus-webapp/Dockerfile
helm/README.md
helm/templates/ingress.yml
helm/templates/webapp.yml
helm/values.yaml

Implementation of a redirection feature which enable to seamlessly present collections hosted by alternate SDAP as provided by a main SDAP.
This pull request requires https://github.com/apache/incubator-sdap-ingester/pull/52 on this ingester so that the ingestion supports (ie ignores) the remote collection configuration.
The ticket describing the developed feature is https://issues.apache.org/jira/browse/SDAP-388
Docker images integrating the feature are available on docker hub:
- ingestion, to ignore remote collections: tloubrieu/collection-manager:0.1.6a15
- webapp: tloubrieu/nexus-webapp:distributed.0.4.5a42
A user oriented documentation has been added in the `helm/README.md` file where the collections.yaml configuration is documented.
The service is deployed on …

Sdap 388 proxy

---

CHANGELOG.md
helm/templates/webapp.yml

2 bugs that I missed to push before I merged the PR https://github.com/apache/incubator-sdap-nexus/pull/162
The deployment of the helm chart fails without these fixes.

fix bugs in helm chart after update for proxy feature

---

CHANGELOG.md
analysis/webservice/algorithms_spark/Matchup.py

Set to be the length of the matches passed as results.
Ran a quick test and it seems to be working (not null anymore and equal to number of matches returned)

Fix for null count field in return for matchup_spark request

---

CHANGELOG.md
analysis/webservice/algorithms_spark/Matchup.py

- Nga was seeing a 500 error when doing satellite to satellite matchup
- Fixed satellite to satellite matchup failure -- was due to ` 'platform': None,` line
- Nga's request was returning "null" instead of data array, even after fixing above error
- Changed behavior where, if > `resultsSizeLimit` results are found, the first `resultsSizeLimit` are returned, rather than returning "None"
- Nga's request was not returning expected results. The primary/secondary points were not identical, as expected.
- This is due to the behavior of `matchOnce`. If `matchOnce` is selected, only one secondary point is returned. The secondary point that is chosen is the point that is closest to the primary point, spatially.
- Updated this to choose the point based on both space AND time. I'm trying to think if …

Fix satellite to satellite matchup

---

CHANGELOG.md
analysis/tests/redirect/test_RemoteSDAPCache.py
analysis/webservice/algorithms/DataSeriesList.py
analysis/webservice/nexus_tornado/app_builders/HandlerArgsBuilder.py
analysis/webservice/nexus_tornado/app_builders/NexusAppBuilder.py
analysis/webservice/redirect/RedirectHandler.py
analysis/webservice/redirect/RemoteSDAPCache.py
analysis/webservice/redirect/__init__.py
analysis/webservice/webapp.py
data-access/requirements.txt
helm/templates/webapp.yml

This pull request completes ticket  https://issues.apache.org/jira/browse/SDAP-388 by providing metadata of the remote collections in the /list end-point.
The remote metadata is cached for 24 hours so to avoid latency on the user end. Note that the list result itself is cached for 1hour.
The implemented feature is deployed on https://aqacf.jpl.nasa.gov/nexus//list

Add metadata to remote coll

---

CHANGELOG.md
analysis/webservice/algorithms/doms/DatasetListQuery.py
analysis/webservice/algorithms_spark/Matchup.py
analysis/webservice/apidocs/openapi.yml

- Fixed openapi issues that was causing unusual swagger behavior
- Updated `/domslist` to use AWS insitu datasets rather than DOMS
- Updated `matchup_spark` to use the above endpoint so insitu datasets are auto populated in secondary dropdown
- Removed dropdown from `matchup_doms` endpoint secondary dropdown
- Added additional language to openapi spec to clarify which insitu API is being used which each matchup endpoint
- Added extra logs to capture additional timing metrics on AWS insitu performance  
(deployment in progress)

Fix matchup bugs

---

CHANGELOG.md
analysis/webservice/redirect/RedirectHandler.py

It appeared to have been caused by an import issue in RedirectHandler.py
Updated import statements and tested with local SDAP. Verified results against SDAP image preceding the error.

Fixed error causing timeSeriesSpark to fail

---

CHANGELOG.md
analysis/webservice/algorithms/doms/ResultsStorage.py
analysis/webservice/algorithms_spark/MatchupDoms.py
analysis/webservice/apidocs/openapi.yml
docker/nexus-webapp/Dockerfile

* Fixed bug introduced in the last PR causing `domsresults` to no longer work. This was because the `details` field names were updated, but the code that inserts results into the database was not. I've updated the code that inserts the details into the database to look for the new field names. `None` is being used for `stats["numGriddedChecked"]` and `stats["numInsituChecked"]` because otherwise we'd need to change the db schema which would cause issues with many existing SDAP deployments. 
* Added link to CDMS Schema endpoint in Swagger in the `parameter` and `platforms` field descriptions
* Added env var `REQUESTS_CA_BUNDLE` env var to Dockerfile. Building the docker image suddenly stopped working the other day with error `Could not find a suitable TLS CA certificate bundle`, so this is …

Matchup domsresults bugfix

---

analysis/webservice/algorithms/HofMoeller.py
analysis/webservice/algorithms_spark/HofMoellerSpark.py
analysis/webservice/redirect/RemoteSDAPCache.py

On the AQ deployment we found a redirect bug that caused the AQ `/nexus/list` to crash when attempting to connect to a remote SDAP. The redirect code was catching `requests.exceptions.ConnectTimeout` exceptions but `requests.exceptions.ReadTimeout` exceptions could also be raised when the remote `/nexus/list` endpoint was unreachable.  This PR addresses that by including `requests.exceptions.ReadTimeout` in the except block. 
This PR also includes a fix to the HofMoeller algorithms. There was a change made to the name of the nexus point data_val variable (from point.data_val to point.data_vals) in nexus model.py's nexus_point_generator. The change in variable name was not updated in the HofMoeller algorithms, so this change is included in the PR.
The fix to the HofMoeller algorithms has …

SDAP-403: Remote timeout fix and HofMoeller bug fix

---

CHANGELOG.md
analysis/tests/algorithms_spark/test_matchup.py
analysis/tests/data/edge_response.json
analysis/webservice/algorithms_spark/Matchup.py

[SDAP-402](https://issues.apache.org/jira/browse/SDAP-402)
- Fixed matchOnce logic. Previously, only a single secondary point was matched to a primary point. Now, we are allowing multiple matches so long as they share the same time and space as the closest point. 
- Fixed the failing matchup unit tests
- Added a new unit test case for this change
- Fixed bug where `depth` was being overwritten with a null value (maybe will fix our depth problems?)
Tested this locally with the following request (from the google doc):
```
{{big_data_url}}/match_spark?tt=43200&primary=JPL-L4-MRVA-CHLA-GLOB-v3.0&secondary=shark-2018&startTime=2018-04-01T00%3A00%3A00Z&endTime=2018-04-01T12%3A59%3A59Z&rt=25000&b=-140%2C10%2C-110%2C40&platforms=3B&depthMin=-5&depthMax=5&matchOnce=true
```
<details>
<summary>This …

SDAP-402: Update matchOnce logic

---

CHANGELOG.md
analysis/webservice/algorithms/doms/config.py
analysis/webservice/algorithms/doms/insitu.py

Added a new provider for NCAR so either the NCAR insitu api or JPL insitu api can be specified. This wasn't really possible due to the way this was written so I had to add an extra field in the insitu config `short_name`. This is optional, and can be specified when executing matching and specifying the secondary dataset. 
With these changes, the following secondary ICOADS values can be provided:
- `ICOADS%20Release%203.0` Uses the NCAR In-Situ API (this is the old method which still works)
- `ICOADS_NCAR` Uses the NCAR In-Situ API
- `ICOADS_JPL` Uses the JPL In-Situ API
Once validated, I'd recommend we revert these changes as they won't be useful in a practical scenario.
---
Testing:
```bash
{{big_data_url}}/match_spark?primary=MUR25-JPL-L4-GLOB-v04.2&secondary=ICOADS%20Release%203.0&start …
```

Add second NCAR provider

---

CHANGELOG.md
analysis/webservice/algorithms_spark/TimeSeriesSpark.py

This PR fixes a bug in the `/timeSeriesSpark` algorithm that would return NaNs in the comparison stats dictionary when comparing two datasets with only one overlapping date. 
ex: Under certain conditions there can be only a single date matchup between DS1 and DS2 which results in the linear regression algorithm used to compute the comparison stats returning NaNs. 
The fix (for now) is to check for NaNs in the results of the linear regression algorithm and set the comparison stats to an empty dictionary, following the precedent set when there are no matching dates. 
This has been tested in SLCP's deployment.

SDAP-406: Fix comparison stats bug in timeseriesspark algorithm

---

CHANGELOG.md
analysis/webservice/algorithms/doms/BaseDomsHandler.py
analysis/webservice/algorithms/doms/DomsInitialization.py
analysis/webservice/algorithms/doms/ResultsStorage.py

[SDAP-407](https://issues.apache.org/jira/browse/SDAP-407)
Currently, depth is not being returned when the `/domsresults` endpoint is called. This is because depth is not stored in the database so that information is lost.
Added depth to the database, after matchup this field is now populated. Updated CSV and NetCDF conversion to make sure this field is present. 
Examples below. Please note the primary dataset is a satellite dataset which is why depth is null/not present. 
Also note that I generated these by running a local instance of Solr/Cassandra and included massively large tolerances to make sure a match would occur. The matches are not valid and were only used for testing purposes. 
```sh
/match_spark?tt=43200&primary=AVHRR_OI_L4_GHRSST_NCEI&secondary=ICOADS_JPL&startTime=2015-01-01 …
```

SDAP-407: Return depth in CSV and NETCDF matchup outputs

---

CHANGELOG.md
analysis/webservice/algorithms/doms/subsetter.py
analysis/webservice/apidocs/openapi.yml

- Removed int requirement from list of platforms
- Made parameter optional
- Updated openapi spec
- Fixed issue in subsetter when multiple platforms are matched. Since this matches with different science variables, it's possible not every science variable will have a value for each row. 
Tested with:
```bash
/cdmssubset?insitu=ICOADS Release 3.0&startTime=2018-10-21T00:00:00Z&endTime=2018-10-22T01:00:00Z&b=-30,15,-45,30&depthMin=0&depthMax=5&platforms=0,16,17,30,41,42&output=ZIP
```
Result looks as expected. [download.zip](https://github.com/apache/incubator-sdap-nexus/files/10136100/download.zip)

cdmssubset bugfix

---

CHANGELOG.md
analysis/webservice/algorithms/doms/DatasetListQuery.py
analysis/webservice/algorithms/doms/ResultsRetrieval.py
analysis/webservice/apidocs/openapi.yml
analysis/webservice/nexus_tornado/app_builders/NexusAppBuilder.py

- Updated platform in match_spark to be multi select
- I think SDAP versioning is working with the /version endpoint so I’ll leave that in.
- Removed /domsvalues and /datainbounds endpoint from SwaggerUI
- Added note to /stats entry in SUI to note it is limited to satellite datasets

SwaggerUI updates & Removal of DOMS terminology

---

CHANGELOG.md
docker/nexus-webapp/Dockerfile
docs/build.rst

Failure seemed to trace back to the python=3.8 install step in the dockerfile, so I restricted the package specifier to install the exact version + build found in a webapp image built prior to this issue. Tested successfully with `--no-cache`.

SDAP-434 + SDAP-447 - Fix for webapp image build failure + image size

---

CHANGELOG.md
analysis/webservice/algorithms_spark/Matchup.py

Prevents duplicate primary points from appearing in result of matchup by implementing object equality for `DomsPoint` class such that different `DomsPoint` objects that happen to correspond to the same primary point are merged in the `combineByKey` step.
This PR does not find/solve the root cause of this issue but does prevent it from effecting the final results.

SDAP 412 - Solution to Duplicate Primary Issue in /match_spark Endpoint

---

CHANGELOG.md
analysis/tests/algorithms_spark/test_matchup.py
analysis/webservice/algorithms_spark/Matchup.py
analysis/webservice/apidocs/openapi.yml

- Added a new query parameter to the matchup algorithm to allow the user to specify whether time or distance should be prioritized
- New parameter is called `prioritizeDistance`
- Default is `true` and param is optional so existing queries do not break 
- Added a new unit test for this parameter
- Added new parameter to openapi specification
Please note this has only been tested using the new unit test due to k8s issues with our deployment.

SDAP-454: Allow user to prioritize whether distance or time is used to determine "closest" match

---

CHANGELOG.md
analysis/webservice/algorithms_spark/Matchup.py

To my understanding, resultSizeLimit should only limit the results that are returned to the user for the match_spark query, but it can also truncate the results that are stored to be fetched by the results endpoint.

SDAP-444 - Fixed resultSizeLimit truncating result storage in match_spark

---

CHANGELOG.md
data-access/nexustiles/nexustiles.py
docker/solr/cloud-init/create-collection.py

We observed Solr storing the lat/lon values as strings instead of double/doubles. This was a very abnormal situation, but we should still handle this to avoid having to reindex data should this happen again

SDAP-459 - Ensure min/max lat/lon values are float

---

.readthedocs.yaml
docs/requirements.txt

In 1.1.0 release, we tried to add copy buttons to the code blocks for the SDAP docs. 
Turns out this was done incompletely and we need to direct RTD to install the relevant Sphinx extension so we can get our builds running successfully.

Readthedocs build failure fix

---

CHANGELOG.md
analysis/webservice/algorithms/doms/BaseDomsHandler.py
analysis/webservice/apidocs/openapi.yml
analysis/webservice/nexus_tornado/request/renderers/NexusCSVRenderer.py
analysis/webservice/nexus_tornado/request/renderers/NexusNETCDFRenderer.py
analysis/webservice/webmodel/NexusResults.py

Matchup output is now written to CDMS_[execution_ID].[csv|nc]. 
Tested locally, the file downloaded was correctly named. 
---
**Note:** There is an existing feature where a `filename` param provided will be used as the output filename. This change does not impact that behavior. If a `filename` param is provided, it will still be used as the output filename. If not, CDMS_[execution_ID].[csv|nc] will be used for the matchup result endpoints. This might be what Shawn was thinking of in terms of doms renaming output files. 
Also added the missing `filename` param to the `/cdmsresults` openapi definition.

Updated matchup output filename

---

analysis/webservice/algorithms/doms/DatasetListQuery.py

Fixes a bug in #261 which causes the `/cdmslist` endpoint to break. Bug was due to the endpoint producing a `DomsQueryResults` object. The pagination PR makes an assumption that one of the fields of this object will be given as non-null, which doesn't apply to the result data for this endpoint. This PR provides the endpoint with its own result type, which should remove all the unused/empty/misleading fields that come with using `DomsQueryResults` or even the base `NexusResults` class.
The changes in this PR will also allow for the closure of #177, as the issue handled by it will no longer exist.

Fix for cdmslist bug in pagination PR

---

CHANGELOG.md
analysis/webservice/algorithms/doms/subsetter.py

When generating CSV headers for variables, it would be assumed that `standard_name` would be defined. That would not always be the case, and this would cause an error. This PR uses `variable_name` as a fallback so datasets without defined standard names can be subsetted.

SDAP-479: Fix cdmssubset failing if standard/variable name not available

---

CHANGELOG.md
data-access/nexustiles/dao/SolrProxy.py
data-access/nexustiles/nexustiles.py

We've been getting issues with Solr's polygon intersection search for certain tile shapes & bounding polys, so let's just use the more reliable bounding box search and mask out the extras.

SDAP-39 - Querying tiles by polygon now uses bbox query where possible

---

CHANGELOG.md
analysis/webservice/algorithms/doms/ExecutionStatus.py
docker/nexus-webapp/Dockerfile
docker/nexus-webapp/install_nexusproto.sh
docs/build.rst

- Ensured links in the `/job` endpoint are https
- SDAP-488: Workaround to build issue on Apple Silicon (M1/M2). Image build installs nexusproto through PyPI instead of building from source. A build arg `BUILD_NEXUSPROTO` was defined to allow building from source if desired

Bring next release candidate up to date w/ master

---

CHANGELOG.md
analysis/webservice/algorithms/doms/config.py
analysis/webservice/algorithms/doms/insitu.py
analysis/webservice/algorithms_spark/Matchup.py

- Cast platform to string. SDAP requires platform to be a string (db col is str) but the DOMS insitu API seems to return an integer.
- Add mechanism for not supporting insitu schema. As far as I know no schema endpoint exists in DOMS, so in this case we'd set the schema endpoint to None. 
- Removed cloud insitu nodes from conf. Added DOMS insitu nodes
---
All testing was done on a local instance of SDAP where Cass/Solr are running locally via Docker. I ingested AVHRR_OI_L4_GHRSST_NCEI 2018-08-01 - 2018-08-16 data prior to running this test.
Test query:
```bash
localhost:8083/match_spark?primary=AVHRR_OI_L4_GHRSST_NCEI&secondary=SAMOS&startTime=2018-08-01T00%3A00%3A00Z&endTime=2018-08-01T23%3A59%3A59Z&b=-122%2C%2026%2C%20-114%2C%2034&platforms=30&depthMin=-1&depthMax=1&tt=43200&rt=18750&mat …
```

SDAP-505: Support DOMS insitu API

---

CHANGELOG.md
analysis/webservice/algorithms/DataSeriesList.py
analysis/webservice/redirect/RemoteSDAPCache.py

This fixes a bug where unreachable remote SDAPs could break the local SDAP calls to `/nexus/list`. Previously, only a few reasons for being unable to connect to the remote SDAP (like timeouts) were being caught, but there are a few additional edge cases to consider. We now check for anything other than a 200. We also needed to adjust the logic for how remote collections were added to the local `/nexus/list`. 
If the remote URL is unreachable, it is logged as a warning and moves on to trying the next remote collection.
ex:
```
2024-05-02T16:47:07 - webservice.redirect.RemoteSDAPCache - WARNING - URL https://aq-sdap.stcenter.net/nexus/list was not reachable
2024-05-02T16:47:07 - webservice.algorithms.DataSeriesList - WARNING - collection PM25 has not been found in url …
```

SDAP 515 - Improved handling of unreachable remote SDAPs

---

CHANGELOG.md
analysis/webservice/apidocs/index.html
analysis/webservice/apidocs/openapi.yml

Added additional analysis algorithms:
- timeAvgMapSpark
- timeSeriesSpark
- dailydifferenceaverage_spark
- latitudeTimeHofMoellerSpark
- longitudeTimeHofMoellerSpark
- maxMinMapSpark
- varianceSpark
Added `Mapping Analytics` section for non-subsetting algorithms that return mappable data. 
Added snippet to `index.html` to try to hide the "Try it out" buttons, but wasn't able to test.
NOTE: this PR supersedes #281

Updates to openapi

---

CHANGELOG.md
analysis/webservice/webapp.py
data-access/nexustiles/nexustiles.py

Originally part of #307 moved to its own PR for the upcoming 1.3.0 release cycle

Changed SDAP startup behavior to wait for all datasets to be ready

---

CHANGELOG.md
data-access/nexustiles/backends/zarr/backend.py

Replaced with error message in endpoint response.
Example:
```json
{
"shortName": "oco3_sams_l3_post_qf",
"title": "oco3_sams_l3_post_qf",
"type": "zarr",
"error": "Dataset is currently unavailable",
"error_reason": "Cannot open dataset (The AWS Access Key Id you provided does not exist in our records.)"
}
```

[SDAP-525] Fix for expired AWS credentials for zarr collections breaking list endpoint

---

CHANGELOG.md
analysis/webservice/algorithms/Tomogram.py

Update the ground and canopy ds arguments to allow 2 collection names, separated by commas. This allows users to specify, for example, a more accurate but less spatially complete (eg Lidar) as the "primary" masking dataset, along with a less accurate but spatially complete (ie, predicted heights from SAR-Lidar fusion) as a "secondary" or "backup" dataset to be used to fill the gaps of the primary. In the event that 2 datasets are specified, their heights are traced onto the output plot.

SDAP-526 - Upgrade canopy and ground masking

---

docs/quickstart.rst
docs/test.rst
tests/README.md
tests/requirements.txt

Tested https://github.com/apache/sdap-nexus/pull/325 with local build of SDAP v1.3.0 and found the following issues
1. Solr failed to start in cloud mode. Setting `ZK_HOST="host.docker.internal:2181/solr"` seemed to fix that issue.
2. When testing satellite-to-satellite matchup got the following error message
```
future: <Future finished exception=InvalidRequest('Error from server: code=2200 [Invalid query] message="Undefined column name message"')>
Traceback (most recent call last):
File "/opt/python/3.9.7/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/incubator-sdap-nexus/analysis/webservice/algorithms_spark/Matchup.py", line 291, in async_calc
storage.updateExecution(
File …
```

SDAP-521 Updated quickstart and test guide.

---

CHANGELOG.md
helm/templates/collection-manager.yml
helm/values.yaml

Simple tweak to add an option to pass `LOG_LEVEL=DEBUG` env variable to the collection manager pod in k8s deployments

SDAP-529 - Added configuration for verbose logging for collection manager in the Helm chart
